export const bankCodeItems = [

  { value: "16852", label: "Alliance Finance Company PLC" },
  { value: "16463", label: "Amana Bank PLC" },
  { value: "16472", label: "Axis Bank" },
  { value: "16010", label: "Bank of Ceylon" },
  { value: "16481", label: "Cargills Bank Limited" },
  { value: "16004", label: "Central Bank of Sri Lanka" },
  { value: "16825", label: "Central Finance PLC" },
  { value: "16047", label: "Citi Bank" },
  { value: "16746", label: "Citizen Development Business Finance PLC" },
  { value: "16056", label: "Commercial Bank PLC" },
  { value: "16870", label: "Commercial Credit & Finance PLC" },
  { value: "16807", label: "Commercial Leasing and Finance" },
  { value: "16205", label: "Deutsche Bank" },
  { value: "16454", label: "DFCC Bank PLC" },
  { value: "16074", label: "Habib Bank Ltd" },
  { value: "16083", label: "Hatton National Bank PLC" },
  { value: "16737", label: "HDFC Bank" },
  { value: "16092", label: "Hongkong Shanghai Bank" },
  { value: "16384", label: "ICICI Bank Ltd" },
  { value: "16108", label: "Indian Bank" },
  { value: "16117", label: "Indian Overseas Bank" },
  { value: "16834", label: "Kanrich Finance Limited" },
  { value: "16861", label: "Lanka Orix Finance PLC" },
  { value: "16773", label: "LB Finance PLC" },
  { value: "16269", label: "MCB Bank Ltd" },
  { value: "16913", label: "Mercantile Investment and Finance PLC" },
  { value: "16898", label: "Merchant Bank of Sri Lanka & Finance PLC" },
  { value: "16214", label: "National Development Bank PLC" },
  { value: "16719", label: "National Savings Bank" },
  { value: "16162", label: "Nations Trust Bank PLC" },
  { value: "16311", label: "Pan Asia Banking Corporation PLC" },
  { value: "16135", label: "Peoples Bank" },
  { value: "16922", label: "People’s Leasing & Finance PLC" },
  { value: "16296", label: "Public Bank" },
  { value: "16755", label: "Regional Development Bank" },
  { value: "16278", label: "Sampath Bank PLC" },
  { value: "16728", label: "Sanasa Development Bank" },
  { value: "16782", label: "Senkadagala Finance PLC" },
  { value: "16287", label: "Seylan Bank PLC" },
  { value: "16038", label: "Standard Chartered Bank" },
  { value: "16144", label: "State Bank of India" },
  { value: "16764", label: "State Mortgage & Investment Bank" },
  { value: "16302", label: "Union Bank of Colombo PLC" },
  { value: "16716", label: "Vallibel Finance PLC" },

];
