import type {Metadata} from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from "@/components/ui/toaster"

const marketingOrigin =
  process.env.NEXT_PUBLIC_MARKETING_SITE_ORIGIN ||
  process.env.NEXT_PUBLIC_MARKETING_ORIGIN ||
  process.env.MARKETING_SITE_ORIGIN ||
  (process.env.MARKETING_SITE_ORIGINS || '').split(',').map(s => s.trim()).filter(Boolean)[0] ||
  '';

export const metadata: Metadata = {
  title: 'B2U QR',
  description: 'Generated by Firebase Studio',

  //PWA Manifest settings
  manifest: '/manifest.json',
  icons: {
    icon: '/icons/icon-192x192.png',
    apple: '/icons/icon-192x192.png',
  }
};

export const viewport = {
  themeColor: '#317EFB',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-body antialiased" suppressHydrationWarning>
        {marketingOrigin ? (
          <script
            dangerouslySetInnerHTML={{ __html: `window.__MARKETING_ORIGIN__ = ${JSON.stringify(marketingOrigin)};` }}
          />
        ) : null}
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
